AWSTemplateFormatVersion: '2010-09-09'
Description: Full infrastructure with EC2, ASG, ALB, RDS

Resources:

  MyLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: my-launch-template-final
      LaunchTemplateData:
        InstanceType: t2.micro
        ImageId: ami-0c02fb55956c7d316
        KeyName: my-key-pair              
        SecurityGroupIds:
          - sg-0e1ce476348c5e51            
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: EC2FromASG

  MyTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      VpcId: vpc-08876a6d42fb72476           
      TargetType: instance
      HealthCheckPath: /

  MyLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: my-alb
      Subnets:
        - subnet-0f4a69a4bb995ccd9a  
        - subnet-0dc37fdf729ea52a1
      SecurityGroups:
      - sg-0e1ce476348c5e51 
      Scheme: internet-facing
      Type: application

  MyListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref MyTargetGroup
      LoadBalancerArn: !Ref MyLoadBalancer
      Port: 80
      Protocol: HTTP

  MyAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: my-asg
      MinSize: '1'
      MaxSize: '3'
      DesiredCapacity: '1'
      VPCZoneIdentifier:
        - subnet-0f4a69a4bb995ccd9a  
        - subnet-0dc37fdf729ea52a1
      LaunchTemplate:
        LaunchTemplateSpecification:
          LaunchTemplateId: !Ref MyLaunchTemplate
          Version: !GetAtt MyLaunchTemplate.LatestVersionNumber
      TargetGroupARNs:
        - !Ref MyTargetGroup

  MyDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "Subnet group for RDS"
      SubnetIds:
        - 	subnet-0f4a69a4bb995ccd9a            
        - 	subnet-0dc37fdf729ea52a1          

  MyDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: mydb-instance
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      Engine: mysql
      MasterUsername: admin
      MasterUserPassword: SecurePassword123!
      DBSubnetGroupName: !Ref MyDBSubnetGroup
      VPCSecurityGroups:
        - 	sg-0e1ce476348c5e511            
      PubliclyAccessible: false
      DeletionProtection: false

