AWSTemplateFormatVersion: '2010-09-09'
Description: Create an EC2 Launch Template with Auto Scaling Group

Resources:
  MyLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: my-ec2-launch-template
      LaunchTemplateData:
        InstanceType: t2.micro
        ImageId: ami-0c02fb55956c7d316   
        KeyName: my-key-pair
        SecurityGroupIds:
          - sg-0e1ce476348c5e511
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: AutoScaledInstance

  MyAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: my-auto-scaling-group
      MinSize: '1'
      MaxSize: '3'
      DesiredCapacity: '1'
      VPCZoneIdentifier:
        - subnet-0f4a69a4bb995ccd9   
      LaunchTemplate:
        LaunchTemplateId: !Ref MyLaunchTemplate
        Version: !GetAtt MyLaunchTemplate.LatestVersionNumber
      Tags:
        - Key: Name
          Value: ASGInstance
          PropagateAtLaunch: true
